version: '3.8'
services:
    paste-it:
        build:
          context: .
          dockerfile: Dockerfile
        ports:
          - "5000:5000"
        environment:
          - NODE_ENV=production
          - HOSTNAME=0.0.0.0
          - PORT=5000
